### ISSUE TITLE
make GDAL_DYNAMIC= fails

### ISSUE THREAD

**Issue by mankoff** [GRASS-GIS/homebrew-grass-dev#1]
I'm trying to build grass-71 on OS X following the instructions here: https://grasswiki.osgeo.org/wiki/Compiling_on_MacOSX_using_homebrew

I get the the following error when trying to build. Something about the GUI, even though I compile with the `--without-gui` flag.

```
~ $ brew install --HEAD grass-71 --without-gui
==> Installing grass-71 from rkrug/head-only
==> Cloning https://svn.osgeo.org/grass/grass/trunk
Updating /Library/Caches/Homebrew/grass-71--svn-HEAD
==> Patching
patching file include/Make/Install.make
Hunk #1 succeeded at 116 (offset 2 lines).
==> ./configure --prefix=/usr/local/Cellar/grass-71/HEAD --enable-shared --with-cxx --with-python --with-blas --with-l
==> make GDAL_DYNAMIC=
Last 15 lines from /Users/mankoff/Library/Logs/Homebrew/grass-71/02.make:
/private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/dbmgr
/private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/psmap
/private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/iclass
/private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/vdigit
/private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/timeline
/private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/gcp
/private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/tplot
--
In case of errors please change into the directory with error and run 'make'.
If you get multiple errors, you need to deal with them in the order they
appear in the error log. If you get an error building a library, you will
also get errors from anything which uses the library.
--
```

**Comment by rkrug** [comment]
Le vendredi 22 janvier 2016, Ken Mankoff notifications@github.com a
écrit :

> I'm trying to build grass-71 on OS X
> 
> I assume you ar using El Capita ?

This has nothing to do with the gui but with SIP in El Capitan. This is
discussed at the moment on the grass-rev list but no solution at the moment
for El Capitan available. Yosemite should still work. I posted a somehow
working solutions on the mailing list, but without homebrew.

> following the instructions here:
> https://grasswiki.osgeo.org/wiki/Compiling_on_MacOSX_using_homebrew
> 
> I get the the following error when trying to build. Something about the
> GUI, even though I compile with the --without-gui flag.
> 
> ~ $ brew install --HEAD grass-71 --without-gui
> ==> Installing grass-71 from rkrug/head-only
> ==> Cloning https://svn.osgeo.org/grass/grass/trunk
> Updating /Library/Caches/Homebrew/grass-71--svn-HEAD
> ==> Patching
> patching file include/Make/Install.make
> Hunk #1 succeeded at 116 (offset 2 lines).
> ==> ./configure --prefix=/usr/local/Cellar/grass-71/HEAD --enable-shared --with-cxx --with-python --with-blas --with-l
> ==> make GDAL_DYNAMIC=
> Last 15 lines from /Users/mankoff/Library/Logs/Homebrew/grass-71/02.make:
> /private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/dbmgr
> /private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/psmap
> /private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/iclass
> /private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/vdigit
> /private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/timeline
> /private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/gcp
> 
> ## /private/tmp/grass-7120160122-51277-15ghvdt/gui/wxpython/tplot
> 
> In case of errors please change into the directory with error and run 'make'.
> If you get multiple errors, you need to deal with them in the order they
> appear in the error log. If you get an error building a library, you will
> 
> ## also get errors from anything which uses the library.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rkrug/homebrew-head-only/issues/1.

## 

Rainer M. Krug, PhD (Conservation Ecology, SUN), MSc (Conservation Biology,
UCT), Dipl. Phys. (Germany)

Centre of Excellence for Invasion Biology
Stellenbosch University
South Africa

Tel :       +33 - (0)9 53 10 27 44
Cell:       +33 - (0)6 85 62 59 98
Fax (F):       +33 - (0)9 58 10 27 44

Fax (D):    +49 - (0)3 21 21 25 22 44

email:      Rainer@krugs.de

Skype:      RMkrug

**Comment by mankoff** [comment]
Yes El Capitan. Thanks for the hint. I'm following instructions here: https://lists.osgeo.org/pipermail/grass-dev/2016-January/078290.html

**Comment by rkrug** [comment]
OK - could you please drop a note if it is working?

**Comment by mankoff** [comment]
Didn't get it working. Decided to just install lightweight Lubuntu VM and run latest grass there.

**Comment by rkrug** [comment]
Another even more lightweight possibility would be Docker. There are some floating around:

https://github.com/wenzeslaus/grass-gis-docker
https://github.com/geo-data/grass-docker
http://courses.neteler.org/fun-docker-grass-gis-software/

**Comment by mankoff** [comment]
Yes I found those when looking into solutions. Since this may be shared with others, I think the VM has a much lower barrier of entry, especially when using OS X. If Docker worked well on OS X, then setting up docker would be easier and could be scripted as part of the literate Org document that is also doing all the grass analysis.

**Comment by rkrug** [comment]
Docker on OS X is really easy - I guess you saw https://docs.docker.com/engine/installation/mac/ . I really like the scripting part (and the fact that you can have fixed versions on the docker hub!).
