### ISSUE TITLE
Unsupported special dependency :python

### ISSUE THREAD

**Issue by wenzeslaus** [GRASS-GIS/homebrew-grass-dev#3]
Building on Travis CI results in (invalid formula, unsupported special dependency, invalid syntax):

```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/grass-gis/homebrew-grass-dev/grass-trunk.rb
grass-trunk: Unsupported special dependency :python
Error: Cannot tap grass-gis/grass-dev: invalid syntax in tap!
```

Corresponding line in the `.rb` file:

```
depends_on :python
```

**Comment by wenzeslaus** [comment]
Probably fixed by 668cc43.

**Comment by rkrug** [comment]
Yes - that looks fine. Thanks

**Comment by rkrug** [comment]
Why does this one has a red "closed" icon? Do I have to mark it as solved?

**Comment by wenzeslaus** [comment]
Whether it was an intention or not, you closed it with your previous
comment. That might be fine since I tried to fix it in 668cc43. I just
don't know if it was the right fix.

**Comment by rkrug** [comment]
It was the right fix. How can we get this green "closed" icon back?

**Comment by wenzeslaus** [comment]
Are you just talking about the colors? I think closed is red and open is green on GitHub. Have you seen these in different colors (on GitHub)? I don't think GitHub has closed as invalid unlike other systems (there are only closed/fixed states and then labels on GitHub).

**Comment by rkrug** [comment]
My fault - I thought there were two "closed" state. Everything is fine. Thanks.
