### ISSUE TITLE
Presumably typo in Mac code?

### ISSUE THREAD

**Issue by rkrug** [GRASS-GIS/homebrew-grass-dev#6]
Hi @neteler @wenzeslaus @landam 

The home-brew build gets an error - presumably a typo in the grass code:

```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `prefer_64_bit?' for OS::Mac:Module
```

See https://travis-ci.org/GRASS-GIS/homebrew-grass-dev/jobs/477710475#L1630 in the log.

**Comment by neteler** [comment]
I cannot find the string 'prefer_64_bit' in GRASS, and it looks like C++ to me. 
Anyone having an idea?

**Comment by rkrug** [comment]
Just googled (should have done it before...) and found https://www.rubydoc.info/github/Homebrew/brew/OS%2FMac:prefer_64_bit%3F . So it seems to be home-brew.

**Comment by rkrug** [comment]
See https://stackoverflow.com/questions/54119119/homebrew-tap-formula-prefer-64-bit-not-found - we are not the only ones.

**Comment by rkrug** [comment]
It was a bug in home-brew - working again.

**Comment by godchou** [comment]
this is bug

**Comment by dheerajchand** [comment]
```==> Reinstalling 1 broken dependent from source:
osgeo/osgeo4mac/grass7-lts
==> Reinstalling osgeo/osgeo4mac/grass7-lts
==> Downloading https://grass.osgeo.org/grass72/source/grass-7.2.3.tar.gz
######################################################################## 100.0%
==> Patching
patching file include/Make/Install.make
Hunk #1 succeeded at 116 (offset 2 lines).
Error: An exception occurred within a child process:
  NoMethodError: undefined method `prefer_64_bit?' for OS::Mac:Module
 ~  brew audit --strict```

**Comment by rkrug** [comment]
Please see https://github.com/GRASS-GIS/homebrew-grass-dev

This repo is not needed anymore.
